name: DormantServers
main: me.preciouso.dormantservers.DormantServers
version: 1.1
author: github.com/Kyu
description: Plugin to shutdown server when not in use, and reboot server upon request
permissions:
  dormantserver.start:
    description: Allows user to start main server